### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by ruupert** [606u/jruls#1]
I saw your post on freebsd forums when I was exactly looking for something that shows me how much the jails are using resources.  Seems to work and looks like a handy tool. 

Maybe you could create a port of it and submit it into the ports tree?

**Comment by 606u** [comment]
Port [submitted](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232994).

**Comment by 606u** [comment]
jruls is [now in FreeBSD ports tree](https://svnweb.freebsd.org/ports?view=revision&revision=489892).
